-- Chart of Accounts seed data
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('A001', 'Cash', 'Current Assets', 'Assets');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('A002', 'Petty Cash', 'Current Assets', 'Assets');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('A003', 'Sulaman HBL', 'Current Assets', 'Assets');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('A004', 'Khakan Bank', 'Current Assets', 'Assets');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('A005', 'Opening Balance', 'Current Assets', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E001', 'Anees Jhang Trip', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E002', 'Appointments', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E003', 'Bank Charges', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E004', 'Bike', 'Other Expense', 'Assets');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E005', 'Breads', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E006', 'Breakfast', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E008', 'Communication', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E009', 'Computer', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E010', 'Courier', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E011', 'Curry', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E012', 'Entertainment', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E013', 'Gala Event', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E014', 'Gardner Salary', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E015', 'Home Expenses', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E016', 'Khakan Bills', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E017', 'Khakan Personal', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E018', 'Meal Staff', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E019', 'Medical Sulaman', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E020', 'Medicine Anees', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E021', 'Medicine Khakan', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E022', 'Mineral Water', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E023', 'Misc', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E024', 'Petrol Anees', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E025', 'Petty Cash', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E026', 'Rashion', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E027', 'Salaries', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E028', 'Sehri Iftari', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E029', 'Stationary', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E030', 'Sulaman HBL', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E031', 'Sunday Meal', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E032', 'Tea', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E033', 'Utility Bills', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E034', 'Water Tanker', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('E035', 'Web Hosting', 'Other Expense', 'Expense');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('L0001', 'Capital', 'Long Term Liability', 'Owner Equity');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('L002', 'Abdullah Khan Safi', 'Short Term Liability', 'Liability');
INSERT INTO Accounts (AccountId, Name, Category, Type) VALUES ('L003', 'Danish Munir', 'Short Term Liability', 'Liability');